### ISSUE TITLE
Compatibility with the Klarna payment plugin 

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/checkout-fees-for-woocommerce#206] opened 2023-11-29 10:48 UTC
**Is your feature request related to a problem? Please describe.**
Our PGBF plugin to be made compatible with the Klarna payments plugin.

Client said: "I would like to add a fee of 3% on all orders for Klarna (integrated as Klarna Payments). The fee is displayed correctly in the shopping cart for Klarna "Pay now" + Klarna "Invoice" but not for Klarna "Split invoice". Why is that? "

**Additional context**
Ticket: https://tychesoftwares.freshdesk.com/a/tickets/59573

**Comment by gaminikhil** [comment] 2024-02-09 15:44
The issue happens when the 'Tax calculation' is set to 'Proportionally' within the 'Germanized WooCommerce' plugin. When the same setting is set to the 'WooCommerce Standard' option, the issue is not replicated. Screenshot: [https://prnt.sc/DQjbfA_pYiZH](url), hence I am closing this issue.

**Closed by gaminikhil** 2024-02-09 15:44 UTC
Labels: type: enhancement, client's requirement
