### ISSUE TITLE
Use Language selected for individual user instead the WordPress Site Language. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/checkout-fees-for-woocommerce#92] opened 2022-04-12 06:06 UTC
**Describe the bug**
My site is in Spanish for a shop in Spain, but I prefer to work in English. My admin account is set to English for that reason. Up to now all plug-ins settings I have seen show the admin user preferred language. Yours is the first exception to this tradition because it shows the site’s default language. In my opinion a plug-in should not oblige administrators to use a language that is not of their choice. 

**To Reproduce**
On Users > Add/Edit User page, I have set Spanish Language - https://prnt.sc/hH6eUw3ptI5d
The plugin language is in English as per My WordPress Site Language- https://prnt.sc/_XMROBW8HGOB

The plugin should show the strings of selected language for users. 

**Additional context**
https://wordpress.org/support/topic/admin-language-not-default-language/

**Comment by apeksha10** [comment] 2022-07-07 11:51
Re-opening this issue.
Take the latest git copy 
1. Select the user's language as France. https://www.screencast.com/t/TNZGjmcaLzB
2. WordPress site language is the English UK
3. Visit the site as logged-in users but our plugin string is not translated in France language. 
https://www.screencast.com/t/l6RURcxDjpw

**Comment by nidhitatosaniya** [comment] 2022-07-07 12:23
Steps : 
1. site language : English

**Comment by nidhitatosaniya** [comment] 2022-07-08 06:09
Steps : 
1. set site language : English
2. set user language : Deutsch https://prnt.sc/N3pqIzePCZ_e
3. Go To Dashboard ---> updates  click on "Update Translation" buttons  https://prnt.sc/2H_OrEcBNz30
4. log-out and login again.
5. see result  https://prnt.sc/iIPRA3Hilfwl
Hence I closing it.

**Comment by apeksha10** [comment] 2022-07-08 12:36
Re-opening this issue,
As this issue does not work with the French language.

Note: I have tested with Espanol, Hebrew, Dutch, etc. Things are working fine with these all languages but with the French language, the issue is replicated. 

Example of when I select Datch lang. 
https://www.screencast.com/t/trwfYW4m
https://www.screencast.com/t/jZDj2q7vlw

Hence re-open this issue ( Discussed with Kartik and Nidhi )

**Comment by nidhitatosaniya** [comment] 2022-07-09 08:49
This is not the issue. For the languages whose translations are already available for our plugin on the [worpress.org](http://worpress.org/) is working fine. You can check available translations for our plugin here - https://prnt.sc/C_fYsA-CRzyf
There is no translation available for the French language hence its not working.

WordPress is fetching the available translation upon the Update Translations button available on the Dashboard->Updates page.

So if you select Hindi language then also it will not work. Because plugin is not translated in Hindi language also.

To verify this with other plugin, see the WooCommerce plugin translations. Hindi translation is not available for WooCommerce hence not strings of the WooCommerce plugin will get translated into Hindi Language.

**Closed by nidhitatosaniya** 2022-07-09 08:49 UTC
Labels: type: enhancement, client's requirement
